echo "expecting you to type in Forged Alliances Launch options";
echo "reminder : look in your home folder, theres a file there with the contents to be pasted";
echo "once thats done edit steam settings in order to enable Proton for all games";
if '$already_fa';
then echo "";
else echo "";
echo "";
echo "";
echo "[$(date --rfc-3339=seconds)] T3 running steam" >> ~/faf.sh-'$faf_sh_version'.log;
steam -login '$steam_user_name' '$steam_password';
rm ~/the\ contents\ of\ this*;
if '$default_dir';
then echo "[$(date --rfc-3339=seconds)] T3 installing FA to default dir" >> ~/faf.sh-'$faf_sh_version'.log;
while [ \( ! -d ~/.steam/steam/steamapps/common/Supreme* \) -a \( ! -d ~/.steam/steam/SteamApps/common/Supreme* \) ];
do steamcmd +login '$steam_user_name' '$steam_password' +@sSteamCmdForcePlatformType windows +app_update 9420 +quit;
done;
else echo "[$(date --rfc-3339=seconds)] T3 installing FA to custom dir" >> ~/faf.sh-'$faf_sh_version'.log;
while [ ! -d '$directory'/bin ];
do steamcmd +login '$steam_user_name' '$steam_password' +@sSteamCmdForcePlatformType windows +force_install_dir '$directory' +app_update 9420 +quit;
done;
cd '$directory';
mkdir -p steamapps/common/Supreme\ Commander\ Forged\ Alliance;
mv * steamapps/common/Supreme\ Commander\ Forged\ Alliance/ 2>/dev/null;
cd;
fi;
echo "[$(date --rfc-3339=seconds)] T3 FA installed condition met" >> ~/faf.sh-'$faf_sh_version'.log;
fi;
echo "[$(date --rfc-3339=seconds)] T3 launching FA" >> ~/faf.sh-'$faf_sh_version'.log;
eval "steam -login '$steam_user_name' '$steam_password' -applaunch 9420 &";
echo "";
if '$default_dir';
then origin="$HOME/.steam/steam";
else origin='$directory';
fi;
echo "waiting for Forged Alliance to be installed, Game.prefs to exits and Forged Alliance to be shut down";
echo "you may also type \"c\" for \"continue\" to exit this loop";
echo "if you feel the conditions for continuing sucessfully";
echo -n "have already been adequately met... ";
\( i=1;
sp="/-\|";
no_config=true;
while $no_config;
do printf "\b${sp:i++%${#sp}:1}";
[[ ! $(pidof SupremeCommande) && -f $origin/steamapps/compatdata/9420/pfx/drive_c/users/steamuser/Local\ Settings/Application\ Data/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Game.prefs ]] && no_config=false;
sleep 1;
done;
kill $$;
\) &;
child_pid=$!;
while $no_config;
do read -r typed_continue;
[[ "$typed_continue" = "c" ]] && no_config=false;
sleep 1;
done;
kill $child_pid;
echo "";
if '$already_fa';
then echo;
else echo "[$(date --rfc-3339=seconds)] T3 copying over run file" >> ~/faf.sh-'$faf_sh_version'.log;
cp -f /tmp/proton_'$real_user'/run ~/faf/;
fi;
echo "[$(date --rfc-3339=seconds)] T3 making symbolic links" >> ~/faf.sh-'$faf_sh_version'.log;
if '$default_dir';
then if [ -d ~/.steam/steam/steamapps ];
then if [ -d ~/.steam/steam/steamapps/common/Supreme* ];
then cd ~/.steam/steam/steamapps/common/Supreme\ Commander\ Forged\ Alliance;
rm -rf Maps;
rm -rf Mods;
ln -s ~/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Maps/ Maps;
ln -s ~/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Mods/ Mods;
else echo "[$(date --rfc-3339=seconds)] T3 steamapps FA folder not found" >> ~/faf.sh-'$faf_sh_version'.log;
fi;
if [ -d ~/.steam/steam/steamapps/compatdata/9420/pfx/drive_c/users/steamuser ];
then cd ~/.steam/steam/steamapps/compatdata/9420/pfx/drive_c/users/steamuser;
rm -rf My\ Documents;
mkdir My\ Documents;
cd My\ Documents;
ln -s ~/My\ Games/ My\ Games;
else echo "[$(date --rfc-3339=seconds)] T3 steamapps FA compatdata folder not found" >> ~/faf.sh-'$faf_sh_version'.log;
fi;
elif [ -d ~/.steam/steam/SteamApps ];
then echo "[$(date --rfc-3339=seconds)] T3 curious case of SteamApps instead of steamapps" >> ~/faf.sh-'$faf_sh_version'.log;
if [ -d ~/.steam/steam/SteamApps/common/Supreme* ];
then cd ~/.steam/steam/SteamApps/common/Supreme\ Commander\ Forged\ Alliance;
rm -rf Maps;
rm -rf Mods;
ln -s ~/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Maps/ Maps;
ln -s ~/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Mods/ Mods;
else echo "[$(date --rfc-3339=seconds)] T3 SteamApps FA folder not found" >> ~/faf.sh-'$faf_sh_version'.log;
fi;
if [ -d ~/.steam/steam/SteamApps/compatdata/9420/pfx/drive_c/users/steamuser ];
then cd ~.steam/steam/SteamApps/compatdata/9420/pfx/drive_c/users/steamuser;
rm -rf My\ Documents;
mkdir My\ Documents;
cd My\ Documents;
ln -s ~/My\ Games/ My\ Games;
else echo "[$(date --rfc-3339=seconds)] T3 SteamApps FA compatdata folder not found" >> ~/faf.sh-'$faf_sh_version'.log;
fi;
else echo "[$(date --rfc-3339=seconds)] T3 neither steamapps nor SteamApps are found. exiting" >> ~/faf.sh-'$faf_sh_version'.log;
exit 1;
fi;
else echo "[$(date --rfc-3339=seconds)] T3 symlinking for non-standart install location" >> ~/faf.sh-'$faf_sh_version'.log;
cd '$directory'/steamapps/common/Supreme\ Commander\ Forged\ Alliance;
rm -rf Maps;
rm -rf Mods;
ln -s ~/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Maps/ Maps;
ln -s ~/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Mods/ Mods;
if [ -d ~/.steam/steam/steamapps ];
then if [ -d ~/.steam/steam/steamapps/compatdata/9420/pfx/drive_c/users/steamuser ];
then cd '$directory'/steamapps/compatdata/9420/pfx/drive_c/users/steamuser;
rm -rf My\ Documents;
mkdir My\ Documents;
cd My\ Documents;
ln -s ~/My\ Games/ My\ Games;
fi;
elif [ -d ~/.steam/steam/SteamApps ];
then if [ -d ~/.steam/steam/SteamApps/compatdata/9420/pfx/drive_c/users/steamuser ];
then cd ~.steam/steam/SteamApps/compatdata/9420/pfx/drive_c/users/steamuser;
rm -rf My\ Documents;
mkdir My\ Documents;
cd My\ Documents;
ln -s ~/My\ Games/ My\ Games;
fi;
fi;
fi;
cd;
source .bashrc;
eval "$(cat .bashrc | tail -n +10)";
echo "[$(date --rfc-3339=seconds)] T3 starting T4 and exiting T3" >> ~/faf.sh-'$faf_sh_version'.log;
