echo "expecting you to type in Forged Alliances Launch options";
echo "reminder : look in your home folder, theres a file there with the contents to be pasted";
echo "once thats done edit steam settings in order to enable Proton for all games";
if $already_fa;
then echo "";
else echo "";
echo "";
echo "";
echo "[$(date --rfc-3339=seconds)] T3 running steam" >> $HOME/faf.sh-?.?.log;
steam -login $steam_user_name $steam_password;
rm $HOME/the\ contents\ of\ this*;
if $default_dir;
then echo "[$(date --rfc-3339=seconds)] T3 installing FA to default dir" >> $HOME/faf.sh-?.?.log;
while [ \( ! -d $HOME/.steam/steam/steamapps/common/Supreme* \) -a \( ! -d $HOME/.steam/steam/SteamApps/common/Supreme* \) ];
do steamcmd +login $steam_user_name $steam_password +@sSteamCmdForcePlatformType windows +app_update 9420 +quit;
done;
else echo "[$(date --rfc-3339=seconds)] T3 installing FA to custom dir" >> $HOME/faf.sh-?.?.log;
while [ ! -d $directory/bin ];
do steamcmd +login $steam_user_name $steam_password +@sSteamCmdForcePlatformType windows +force_install_dir $directory +app_update 9420 +quit;
done;
cd $directory;
mkdir -p steamapps/common/Supreme\ Commander\ Forged\ Alliance;
mv * steamapps/common/Supreme\ Commander\ Forged\ Alliance/ 2>/dev/null;
cd;
fi;
echo "[$(date --rfc-3339=seconds)] T3 FA installed condition met" >> $HOME/faf.sh-?.?.log;
fi;
echo "[$(date --rfc-3339=seconds)] T3 launching FA" >> $HOME/faf.sh-?.?.log;
eval "steam -login $steam_user_name $steam_password -applaunch 9420 &";
echo "";
if $default_dir;
then origin="$HOME/.steam/steam";
else origin=$directory;
fi;
echo "waiting for Forged Alliance to be installed, Game.prefs to exits and Forged Alliance to be shut down";
echo "you may also type \"c\" for \"continue\" to exit this loop";
echo "if you feel the conditions for continuing sucessfully";
echo -n "have already been adequately met... ";
i=1;
sp="/-\|";
no_config=true;
( while $no_config;
do printf "\b${sp:i++%${#sp}:1}";
[[ ! $(pidof SupremeCommande) && -f $origin/steamapps/compatdata/9420/pfx/drive_c/users/steamuser/Local\ Settings/Application\ Data/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Game.prefs ]] && no_config=false;
sleep 1;
done;
kill $$;
) &
child_pid=$!;
while $no_config;
do read -r typed_continue;
[[ "$typed_continue" = "c" ]] && no_config=false;
sleep 1;
done;
kill $child_pid;
echo "";
if $already_fa;
then echo;
else echo "[$(date --rfc-3339=seconds)] T3 copying over run file" >> $HOME/faf.sh-?.?.log;
cp -f /tmp/proton_'$real_user'/run $HOME/faf/;
fi;
echo "[$(date --rfc-3339=seconds)] T3 making symbolic links" >> $HOME/faf.sh-?.?.log;
if $default_dir;
then if [ -d $HOME/.steam/steam/steamapps ];
then if [ -d $HOME/.steam/steam/steamapps/common/Supreme* ];
then cd $HOME/.steam/steam/steamapps/common/Supreme\ Commander\ Forged\ Alliance;
rm -rf Maps;
rm -rf Mods;
ln -s $HOME/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Maps/ Maps;
ln -s $HOME/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Mods/ Mods;
else echo "[$(date --rfc-3339=seconds)] T3 steamapps FA folder not found" >> $HOME/faf.sh-?.?.log;
fi;
if [ -d $HOME/.steam/steam/steamapps/compatdata/9420/pfx/drive_c/users/steamuser ];
then cd $HOME/.steam/steam/steamapps/compatdata/9420/pfx/drive_c/users/steamuser;
rm -rf My\ Documents;
mkdir My\ Documents;
cd My\ Documents;
ln -s $HOME/My\ Games/ My\ Games;
else echo "[$(date --rfc-3339=seconds)] T3 steamapps FA compatdata folder not found" >> $HOME/faf.sh-?.?.log;
fi;
elif [ -d $HOME/.steam/steam/SteamApps ];
then echo "[$(date --rfc-3339=seconds)] T3 curious case of SteamApps instead of steamapps" >> $HOME/faf.sh-?.?.log;
if [ -d $HOME/.steam/steam/SteamApps/common/Supreme* ];
then cd $HOME/.steam/steam/SteamApps/common/Supreme\ Commander\ Forged\ Alliance;
rm -rf Maps;
rm -rf Mods;
ln -s $HOME/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Maps/ Maps;
ln -s $HOME/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Mods/ Mods;
else echo "[$(date --rfc-3339=seconds)] T3 SteamApps FA folder not found" >> $HOME/faf.sh-?.?.log;
fi;
if [ -d $HOME/.steam/steam/SteamApps/compatdata/9420/pfx/drive_c/users/steamuser ];
then cd $HOME.steam/steam/SteamApps/compatdata/9420/pfx/drive_c/users/steamuser;
rm -rf My\ Documents;
mkdir My\ Documents;
cd My\ Documents;
ln -s $HOME/My\ Games/ My\ Games;
else echo "[$(date --rfc-3339=seconds)] T3 SteamApps FA compatdata folder not found" >> $HOME/faf.sh-?.?.log;
fi;
else echo "[$(date --rfc-3339=seconds)] T3 neither steamapps nor SteamApps are found. exiting" >> $HOME/faf.sh-?.?.log;
exit 1;
fi;
else echo "[$(date --rfc-3339=seconds)] T3 symlinking for non-standart install location" >> $HOME/faf.sh-?.?.log;
cd $directory/steamapps/common/Supreme\ Commander\ Forged\ Alliance;
rm -rf Maps;
rm -rf Mods;
ln -s $HOME/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Maps/ Maps;
ln -s $HOME/My\ Games/Gas\ Powered\ Games/Supreme\ Commander\ Forged\ Alliance/Mods/ Mods;
if [ -d $HOME/.steam/steam/steamapps ];
then if [ -d $HOME/.steam/steam/steamapps/compatdata/9420/pfx/drive_c/users/steamuser ];
then cd $directory/steamapps/compatdata/9420/pfx/drive_c/users/steamuser;
rm -rf My\ Documents;
mkdir My\ Documents;
cd My\ Documents;
ln -s $HOME/My\ Games/ My\ Games;
fi;
elif [ -d $HOME/.steam/steam/SteamApps ];
then if [ -d $HOME/.steam/steam/SteamApps/compatdata/9420/pfx/drive_c/users/steamuser ];
then cd $HOME/.steam/steam/SteamApps/compatdata/9420/pfx/drive_c/users/steamuser;
rm -rf My\ Documents;
mkdir My\ Documents;
cd My\ Documents;
ln -s $HOME/My\ Games/ My\ Games;
fi;
fi;
fi;
cd;
source .bashrc;
eval "$(cat .bashrc | tail -n +10)";
echo "[$(date --rfc-3339=seconds)] T3 starting T4 and exiting T3" >> $HOME/faf.sh-?.?.log;
